# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e65b2d84f960c25bb62f73baebc0039abaf352fa6d55d164478abc15f30d5aa6d6d95ed7d63482efa58ff447ca0e9d8a694986c4f9bdb14a7fc74cbf8b4a8090

test:
  secret_key_base: 0d326c23b3053f98a1fcaca7ff9e783c297775462c2f51d142f41620c8d96e45a3171b06b8c16ea4c756fef67b9f9dca4c5f83f1e95bb9fb3f7dbbb59df2ea7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
